name: central-finite-curve-dragoons

plugins:
  - name: vyper
  - name: foundry
  - name: etherscan
  - name: fantom

geth:
  fantom:
    opera:
      uri: https://rpc2.fantom.network
    testnet:
      uri: https://fantom-testnet.drpc.org